# Generated by Django 6.0.2 on 2026-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
