# Generated by Django 6.0.2 on 2026-04-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_alter_expense_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
